require_relative '../lib/models/computer_player'
require_relative '../lib/models/human_player'
require_relative '../lib/models/player'
require_relative '../lib/models/board'
require_relative '../lib/views/view'
require_relative '../lib/controllers/games_controller'